### ISSUE TITLE
Lag in bot lane

### ISSUE THREAD

**Issue by Darkaim63** [Tadaashii/Libellule#2]
Whenever I play wit the mod in botlane it is noticeably laggier

Easily reproducible by playing a matchmade game with Yasuo bot and Libellule and you'll notice the dip in FPS

**Comment by Tadaashii** [comment]
That's kinda weird, because it works fine to me, did you try fantome or lcs instead?

**Comment by Darkaim63** [comment]
I should've mentioned that I am running it through LCS

**Comment by Darkaim63** [comment]
> That's kinda weird, because it works fine to me, did you try fantome or lcs instead?

I should've mentioned that I am running it through LCS

**Comment by Darkaim63** [comment]
TBH I'm still not quite sure how to use the program

**Comment by Darkaim63** [comment]
Update: Game pretty much lags no matter what, only in certain spots on summoners rift

**Comment by Darkaim63** [comment]
Update 2: I pretty much have fixed the issue by playing the game in fullscreen, not a perfect solution but it works.
